### ISSUE TITLE
Tab Display error, cant find how to reach you sorry

### ISSUE THREAD

**Issue by jswhisperer** [enfp-dev-studio/node-mac-request-review#1]
On macos Ventura M1

https://gist.github.com/gregpalaci/91d932e6eca475fa803e2db880494337

**Comment by enfp-dev-studio** [comment]
Thank you so much for leaving a message. It seems like this issue might be related to the Mac Arm64 processor, and I'll do my best to investigate it as soon as possible. In the meantime, I'll leave a warning to not use it on M1 devices and block its usage until the problem is resolved. I've moved this issue to the following link.
